INSERT INTO PRODUCT VALUES(1, 'Ordinateur', 1100);
INSERT INTO PRODUCT VALUES(2, 'Tablette', 1200);
INSERT INTO PRODUCT VALUES(3, 'Switch', 150);
INSERT INTO PRODUCT VALUES(4, 'Routeur', 850);
INSERT INTO PRODUCT VALUES (5, 'Ordinateur de bureau', 1200);
INSERT INTO PRODUCT VALUES (6, 'Clé usb', 12)

